"use client";

import * as React from "react";
import { Linkedin, Sparkles } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { LinkedInShareDialog } from "@/components/linkedin-share-dialog";

const INTRO_TEXT = "I have received the following feedback summary from my colleagues:";
const OUTRO_TEXT = "#Feedback #HTWG #Wachstum";

export function FeedbackSummaryDialog({ open, onOpenChange, summary }) {
  const [editedSummary, setEditedSummary] = React.useState(summary || "");
  const [linkedInOpen, setLinkedInOpen] = React.useState(false);
  const [linkedInText, setLinkedInText] = React.useState("");

  React.useEffect(() => {
    if (open) setEditedSummary(summary || "");
  }, [open, summary]);

  const handleShareClick = () => {
    const composedText = `${INTRO_TEXT}\n\n${editedSummary}\n\n${OUTRO_TEXT}`;
    setLinkedInText(composedText);
    onOpenChange(false);
    // Small delay so the first dialog finishes closing before the second opens
    setTimeout(() => setLinkedInOpen(true), 150);
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              My Feedback Summary
            </DialogTitle>
            <DialogDescription>
              This summary was generated by AI based on all feedback you have received. You can edit it before sharing.
            </DialogDescription>
          </DialogHeader>

          <div className="py-2 space-y-3">
            <p className="text-sm text-muted-foreground">{INTRO_TEXT}</p>
            <Textarea
              value={editedSummary}
              onChange={(e) => setEditedSummary(e.target.value)}
              rows={6}
              className="resize-none text-sm leading-relaxed"
            />
            <p className="text-sm text-muted-foreground">{OUTRO_TEXT}</p>
          </div>

          <DialogFooter className="gap-2 sm:gap-0">
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Close
            </Button>
            <Button
              onClick={handleShareClick}
              className="bg-blue-600 hover:bg-blue-700 text-white"
            >
              <Linkedin className="h-4 w-4 mr-2" />
              Share on LinkedIn
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <LinkedInShareDialog
        open={linkedInOpen}
        onOpenChange={setLinkedInOpen}
        defaultText={linkedInText}
      />
    </>
  );
}
