"use client";

import * as React from "react";
import { Linkedin, Sparkles } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { LinkedInShareDialog } from "@/components/linkedin-share-dialog";

function buildLinkedInFramingText(summary, userName) {
  const name = userName ? `${userName} ` : "";
  return `${name}has received the following feedback summary from colleagues:\n\n${summary}\n\n#Feedback #HTWG #Wachstum`;
}

export function FeedbackSummaryDialog({ open, onOpenChange, summary, userName }) {
  const [linkedInOpen, setLinkedInOpen] = React.useState(false);

  const handleShareClick = () => {
    onOpenChange(false);
    // Small delay so the first dialog finishes closing before the second opens
    setTimeout(() => setLinkedInOpen(true), 150);
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              My Feedback Summary
            </DialogTitle>
            <DialogDescription>
              This summary was generated by AI based on all feedback you have received.
            </DialogDescription>
          </DialogHeader>

          <div className="py-2">
            <p className="text-sm leading-relaxed whitespace-pre-wrap">{summary}</p>
          </div>

          <DialogFooter className="gap-2 sm:gap-0">
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Close
            </Button>
            <Button
              onClick={handleShareClick}
              className="bg-blue-600 hover:bg-blue-700 text-white"
            >
              <Linkedin className="h-4 w-4 mr-2" />
              Share on LinkedIn
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <LinkedInShareDialog
        open={linkedInOpen}
        onOpenChange={setLinkedInOpen}
        defaultText={summary ? buildLinkedInFramingText(summary, userName) : ""}
      />
    </>
  );
}
